[package]
name = "toypay"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "main"
path = "bin/main.rs"

[dependencies]
csv = "1.3.1"
serde = {version="1.0.219", features = ["derive"] }
anyhow = "1.0.98"
rust_decimal = "1.37.2"
lru = "0.16.0"
ahash = "0.8.12"